name: SCA - Dependency Check (BT)
on:
  workflow_call:
    secrets:
      NVD_API_KEY:
        required: false
      DOJO_TOKEN: 
        required: false
      DOJO_URL: 
        required: false
        
jobs:
   SCA:
    name: SCA - Dependency Check Analysis (BT)
    runs-on:  ubuntu-latest
    steps:
    
      - name: Checkout project sources
        uses: actions/checkout@v4
        
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Cache Dependency-Check Data
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/dependency-check-data
          key: ${{ runner.os }}-dependency-check-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-dependency-check
          
      - name: Build with Gradle Wrapper & Run Dependency-Check
        uses: gradle/gradle-build-action@v2.11.1
        with:
          gradle-version: wrapper
          arguments: dependencyCheckAnalyze --info
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
          
      - name: Upload results - SCA
        uses: actions/upload-artifact@master
        with:
           name: Dependency Check Report
           path: ${{github.workspace}}/build/reports/dependency-check-report.html

      # Posts the result of the scan to DefectDojo
      - name: Send report to DefectDojo
        if: (github.repository_owner == 'eu-digital-identity-wallet' && github.ref_name == 'main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch'))
        run: |
          export "FILE=$(find . -type f -name "*dependency-check-report.xml")"
          if [[ -z "$FILE" ]]; then exit 0; fi
          curl -s https://raw.githubusercontent.com/eu-digital-identity-wallet/eudi-infra-ci/main/engagementids.json > engagementids.json
          export "ID=$(jq '."${{ github.repository }}".${{ github.ref_name }}.scaID' engagementids.json)"
          export "SCAN_DATE=$(TZ='EET' date '+%Y-%m-%d')"
          curl -X POST "$DOJO_URL/api/v2/reimport-scan/" \
                            -H "Authorization: Token $DOJO_TOKEN" \
                            -F "active=true" \
                            -F "scan_type=Dependency Check Scan" \
                            -F "minimum_severity=Info" \
                            -F "skip_duplicates=true" \
                            -F "close_old_findings=true" \
                            -F "file=@build/reports/dependency-check-report.xml" \
                            -F "scan_date=$SCAN_DATE" \
                            -F "auto_create_context=True" \
                            -F "product_name=${{ github.repository }}-${{ github.ref_name }}" \
                            -F "engagement_name=Software Composition Analysis - ${{ github.repository }}-${{ github.ref_name }}"
        env:
         DOJO_TOKEN: ${{ secrets.DOJO_TOKEN }}
         DOJO_URL: ${{ secrets.DOJO_URL }}
