name: Secret Scanning - Gitleaks
on:
  workflow_call:
    secrets:
      DOJO_TOKEN: 
        required: false
      DOJO_URL: 
        required: false
        
jobs:
  Secret_Scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks from container
        run: |
            docker create --name GL --entrypoint /bin/bash --interactive --volume ${{ github.workspace }}:/src zricethezav/gitleaks 
            docker start GL
            docker exec GL git config --global --add safe.directory '/src'
            docker exec --user $(id -u):$(id -g) GL gitleaks detect --source=/src --verbose -c /src/security/gitleaks/gitleaks.toml --report-path /src/gitleaks-report.json
        continue-on-error: true

      - name: upload_artifacts   
        uses: actions/upload-artifact@v4
        with:
          name: Gitleaks Artifact Upload
          path:  ${{ github.workspace }}/gitleaks-report.json

      - name: Send report to DefectDojo
        if: (github.repository_owner == 'eu-digital-identity-wallet' && github.ref_name == 'main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch'))
        run: |
          curl -s https://raw.githubusercontent.com/eu-digital-identity-wallet/eudi-infra-ci/main/engagementids.json > engagementids.json
          export "ID=$(jq '."${{ github.repository }}".${{ github.ref_name }}.secretscanningID' engagementids.json)"
          export "SCAN_DATE=$(TZ='EET' date '+%Y-%m-%d')"
          curl -X POST "$DOJO_URL/api/v2/reimport-scan/" \
                            -H "Authorization: Token $DOJO_TOKEN" \
                            -F "active=true" \
                            -F "scan_type=Gitleaks Scan" \
                            -F "minimum_severity=Info" \
                            -F "skip_duplicates=true" \
                            -F "close_old_findings=true" \
                            -F "file=@gitleaks-report.json" \
                            -F "scan_date=$SCAN_DATE" \
                            -F "auto_create_context=True" \
                            -F "product_name=${{ github.repository }}-${{ github.ref_name }}" \
                            -F "engagement_name=Secret Scanning - ${{ github.repository }}-${{ github.ref_name }}"
        env:
         DOJO_TOKEN: ${{ secrets.DOJO_TOKEN }}
         DOJO_URL: ${{ secrets.DOJO_URL }}
